"""
Module: historical_context_policy.py

Purpose:
    Centralize historical-context fallback priors and modifier thresholds.

Role in the System:
    Historical insight artifacts provide the preferred research evidence. This
    policy holds the behavior-preserving fallback constants used when live code
    needs deterministic defaults or when generated artifacts do not provide a
    specific bucket/interaction rule.
"""

from __future__ import annotations


HISTORICAL_CONTEXT_POLICY_VERSION = "historical_context_policy_v1"


HISTORICAL_CONTEXT_POLICY = {
    "policy_version": HISTORICAL_CONTEXT_POLICY_VERSION,
    "owner": "Quant Engines",
    "purpose": "Behavior-preserving historical-context fallback priors and live modifier governance.",
    "tunability": "research_after_forward_evidence",
    "evidence_requirement": "Walk-forward regime validation before live threshold changes.",
    "baseline_expected_range_bps": 143.62,
    "baseline_expected_abs_move_bps": 83.92,
    "vix_low_upper": 13.61,
    "vix_low_expected_range_bps": 79.11,
    "vix_low_expected_abs_move_bps": 48.67,
    "vix_low_sample_profile": "low realized range / compressed movement",
    "vix_low_mid_upper": 15.84,
    "vix_low_mid_expected_range_bps": 97.88,
    "vix_low_mid_expected_abs_move_bps": 59.16,
    "vix_low_mid_sample_profile": "below-median realized range",
    "vix_mid_upper": 18.69,
    "vix_mid_expected_range_bps": 118.07,
    "vix_mid_expected_abs_move_bps": 71.63,
    "vix_mid_sample_profile": "median realized range",
    "vix_high_mid_upper": 24.06,
    "vix_high_mid_expected_range_bps": 136.71,
    "vix_high_mid_expected_abs_move_bps": 83.07,
    "vix_high_mid_sample_profile": "elevated realized range",
    "vix_high_upper": None,
    "vix_high_expected_range_bps": 262.25,
    "vix_high_expected_abs_move_bps": 156.72,
    "vix_high_sample_profile": "high realized range / shock-prone movement",
    "sp500_bottom_quintile_pct": -0.624,
    "sp500_top_quintile_pct": 0.748,
    "nasdaq_bottom_quintile_pct": -0.819,
    "nasdaq_top_quintile_pct": 0.964,
    "nasdaq_direction_evidence_weight": 0.75,
    "us_vix_drop_quintile_pct": -5.189,
    "us_vix_jump_quintile_pct": 4.83,
    "global_prior_direction_threshold": 1.0,
    "global_prior_preview_score_multiplier": 3.0,
    "global_prior_preview_probability_multiplier": 0.015,
    "global_prior_preview_probability_cap": 0.045,
    "near_wall_threshold_pct": 0.35,
    "near_max_pain_threshold_pct": 0.50,
    "strong_prior_override_score": 1.75,
    "expiry_bucket_0_1d_upper": 1.0,
    "expiry_bucket_2_3d_upper": 3.0,
    "expiry_bucket_4_7d_upper": 7.0,
    "expiry_bucket_8_14d_upper": 14.0,
    "trend_selloff_upper_bps": -500.0,
    "trend_weak_upper_bps": -150.0,
    "trend_flat_upper_bps": 150.0,
    "trend_strong_upper_bps": 500.0,
    "vol_bucket_low_score_adjustment": -4,
    "vol_bucket_low_probability_adjustment": -0.040,
    "vol_bucket_low_mid_score_adjustment": -2,
    "vol_bucket_low_mid_probability_adjustment": -0.025,
    "vol_bucket_mid_score_adjustment": 0,
    "vol_bucket_mid_probability_adjustment": -0.010,
    "vol_bucket_high_mid_score_adjustment": 1,
    "vol_bucket_high_mid_probability_adjustment": 0.010,
    "vol_bucket_high_score_adjustment": 4,
    "vol_bucket_high_probability_adjustment": 0.040,
    "interaction_directional_mean_threshold_bps": 5.0,
    "interaction_call_hit_up_threshold": 0.58,
    "interaction_put_hit_up_threshold": 0.45,
    "interaction_edge_mean_divisor_bps": 7.0,
    "interaction_edge_min": 1,
    "interaction_edge_max": 4,
    "interaction_strong_call_hit_up_threshold": 0.62,
    "interaction_strong_put_hit_up_threshold": 0.46,
    "interaction_min_sample_for_full_edge": 80,
    "interaction_probability_cap": 0.025,
    "interaction_probability_mean_divisor_bps": 1200.0,
    "interaction_conflict_edge_threshold": 2,
    "interaction_conflict_threshold_adjustment": 1,
    "interaction_conflict_composite_adjustment": 1,
    "interaction_conflict_size_multiplier": 0.90,
    "interaction_aligned_edge_threshold": 3,
    "interaction_aligned_threshold_adjustment": -1,
    "range_interaction_high_multiplier": 1.25,
    "range_interaction_low_multiplier": 0.75,
    "range_interaction_high_score_adjustment": 2,
    "range_interaction_high_probability_adjustment": 0.015,
    "range_interaction_high_threshold_adjustment": -1,
    "range_interaction_low_score_adjustment": -3,
    "range_interaction_low_probability_adjustment": -0.025,
    "range_interaction_low_threshold_adjustment": 1,
    "range_interaction_low_size_multiplier": 0.92,
    "interaction_score_clip_min": -6,
    "interaction_score_clip_max": 6,
    "interaction_probability_clip_min": -0.040,
    "interaction_probability_clip_max": 0.040,
    "interaction_threshold_clip_min": -2,
    "interaction_threshold_clip_max": 3,
    "interaction_composite_clip_min": -1,
    "interaction_composite_clip_max": 2,
    "interaction_size_clip_min": 0.75,
    "interaction_size_clip_max": 1.0,
    "prior_override_score_cap": 6,
    "prior_override_score_multiplier": 2.0,
    "prior_override_probability_cap": 0.035,
    "prior_override_probability_multiplier": 0.012,
    "prior_override_threshold_adjustment": -1,
    "prior_aligned_score_cap": 8,
    "prior_aligned_score_multiplier": 3.0,
    "prior_aligned_probability_cap": 0.045,
    "prior_aligned_probability_multiplier": 0.015,
    "prior_aligned_strong_score": 2.0,
    "prior_aligned_threshold_adjustment": -1,
    "prior_aligned_strong_threshold_adjustment": -2,
    "prior_aligned_strong_composite_adjustment": -1,
    "prior_conflict_score_cap": 10,
    "prior_conflict_score_multiplier": 4.0,
    "prior_conflict_probability_cap": 0.050,
    "prior_conflict_probability_multiplier": 0.018,
    "prior_conflict_threshold_adjustment": 3,
    "prior_conflict_composite_adjustment": 2,
    "prior_conflict_size_multiplier": 0.75,
    "pcr_high_put_score_adjustment": -4,
    "pcr_high_put_probability_adjustment": -0.020,
    "pcr_high_put_threshold_adjustment": 2,
    "pcr_high_put_composite_adjustment": 1,
    "pcr_high_put_size_multiplier": 0.85,
    "pcr_high_call_score_adjustment": 2,
    "pcr_high_call_probability_adjustment": 0.010,
    "pcr_high_neutral_score_adjustment": -1,
    "pcr_high_neutral_probability_adjustment": -0.005,
    "near_max_pain_score_adjustment": -2,
    "near_max_pain_probability_adjustment": -0.010,
    "near_max_pain_threshold_adjustment": 1,
    "near_max_pain_size_multiplier": 0.90,
    "wall_two_sided_score_adjustment": -2,
    "wall_two_sided_probability_adjustment": -0.010,
    "wall_two_sided_threshold_adjustment": 1,
    "wall_two_sided_size_multiplier": 0.90,
    "wall_direction_friction_score_adjustment": -3,
    "wall_direction_friction_probability_adjustment": -0.015,
    "wall_direction_friction_threshold_adjustment": 1,
    "wall_direction_friction_size_multiplier": 0.88,
    "wall_opposite_support_score_adjustment": 1,
    "wall_opposite_support_probability_adjustment": 0.005,
    "live_score_clip_min": -14,
    "live_score_clip_max": 12,
    "live_probability_clip_min": -0.080,
    "live_probability_clip_max": 0.080,
    "live_trade_strength_threshold_clip_min": -3,
    "live_trade_strength_threshold_clip_max": 6,
    "live_composite_threshold_clip_min": -2,
    "live_composite_threshold_clip_max": 5,
    "live_size_clip_min": 0.50,
    "live_size_clip_max": 1.0,
}


def get_historical_context_policy():
    """
    Return the historical-context fallback policy after active pack overrides.
    """
    from config.policy_resolver import resolve_mapping

    return resolve_mapping("historical_context.core", HISTORICAL_CONTEXT_POLICY)
